//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalPatcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastXMLfolder {
            get {
                return ((string)(this["LastXMLfolder"]));
            }
            set {
                this["LastXMLfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPATCHfolder {
            get {
                return ((string)(this["LastPATCHfolder"]));
            }
            set {
                this["LastPATCHfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBINfolder {
            get {
                return ((string)(this["LastBINfolder"]));
            }
            set {
                this["LastBINfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint SuppressAfter {
            get {
                return ((uint)(this["SuppressAfter"]));
            }
            set {
                this["SuppressAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugOn {
            get {
                return ((bool)(this["DebugOn"]));
            }
            set {
                this["DebugOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutorefreshCVNlist {
            get {
                return ((bool)(this["AutorefreshCVNlist"]));
            }
            set {
                this["AutorefreshCVNlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutorefreshFileinfo {
            get {
                return ((bool)(this["AutorefreshFileinfo"]));
            }
            set {
                this["AutorefreshFileinfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindowPersistence {
            get {
                return ((bool)(this["MainWindowPersistence"]));
            }
            set {
                this["MainWindowPersistence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MainWindowSize"]));
            }
            set {
                this["MainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size EditXMLWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["EditXMLWindowSize"]));
            }
            set {
                this["EditXMLWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState EditXMLWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["EditXMLWindowState"]));
            }
            set {
                this["EditXMLWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditXMLWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["EditXMLWindowLocation"]));
            }
            set {
                this["EditXMLWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FileSelectionWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["FileSelectionWindowSize"]));
            }
            set {
                this["FileSelectionWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FileSelectionWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FileSelectionWindowState"]));
            }
            set {
                this["FileSelectionWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FileSelectionWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["FileSelectionWindowLocation"]));
            }
            set {
                this["FileSelectionWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TableEditorWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TableEditorWindowSize"]));
            }
            set {
                this["TableEditorWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState TableEditorWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["TableEditorWindowState"]));
            }
            set {
                this["TableEditorWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TableEditorWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["TableEditorWindowLocation"]));
            }
            set {
                this["TableEditorWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TableEditorAutoResize {
            get {
                return ((bool)(this["TableEditorAutoResize"]));
            }
            set {
                this["TableEditorAutoResize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TunerWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TunerWindowSize"]));
            }
            set {
                this["TunerWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState TunerWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["TunerWindowState"]));
            }
            set {
                this["TunerWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TunerWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["TunerWindowLocation"]));
            }
            set {
                this["TunerWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmGraphicsWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["frmGraphicsWindowSize"]));
            }
            set {
                this["frmGraphicsWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmGraphicsWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmGraphicsWindowState"]));
            }
            set {
                this["frmGraphicsWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmGraphicsWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmGraphicsWindowLocation"]));
            }
            set {
                this["frmGraphicsWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disableTunerAutoloadSettings {
            get {
                return ((bool)(this["disableTunerAutoloadSettings"]));
            }
            set {
                this["disableTunerAutoloadSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TableName,Category,Units,Columns,Rows,TableDescription")]
        public string TunerModeColumns {
            get {
                return ((string)(this["TunerModeColumns"]));
            }
            set {
                this["TunerModeColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigModeColumnOrder {
            get {
                return ((string)(this["ConfigModeColumnOrder"]));
            }
            set {
                this["ConfigModeColumnOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigModeColumnWidth {
            get {
                return ((string)(this["ConfigModeColumnWidth"]));
            }
            set {
                this["ConfigModeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TunerModeColumnWidth {
            get {
                return ((string)(this["TunerModeColumnWidth"]));
            }
            set {
                this["TunerModeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TunerLogWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TunerLogWindowSize"]));
            }
            set {
                this["TunerLogWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PatcherSplitterDistance {
            get {
                return ((int)(this["PatcherSplitterDistance"]));
            }
            set {
                this["PatcherSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font TableEditorFont {
            get {
                return ((global::System.Drawing.Font)(this["TableEditorFont"]));
            }
            set {
                this["TableEditorFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size frmTdWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["frmTdWindowSize"]));
            }
            set {
                this["frmTdWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmTdWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmTdWindowState"]));
            }
            set {
                this["frmTdWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmTdWindowLocaction {
            get {
                return ((global::System.Drawing.Point)(this["frmTdWindowLocaction"]));
            }
            set {
                this["frmTdWindowLocaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MassCompareWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MassCompareWindowSize"]));
            }
            set {
                this["MassCompareWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MassCompareWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MassCompareWindowState"]));
            }
            set {
                this["MassCompareWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MassCompareWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MassCompareWindowLocation"]));
            }
            set {
                this["MassCompareWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MassCompareSplitWidth {
            get {
                return ((int)(this["MassCompareSplitWidth"]));
            }
            set {
                this["MassCompareSplitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MassModifyTableDataWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MassModifyTableDataWindowSize"]));
            }
            set {
                this["MassModifyTableDataWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MassModifyTableDataWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MassModifyTableDataWindowState"]));
            }
            set {
                this["MassModifyTableDataWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MassModifyTableDataWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MassModifyTableDataWindowLocation"]));
            }
            set {
                this["MassModifyTableDataWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MassModifyTableDataWindowSplitterDistance {
            get {
                return ((int)(this["MassModifyTableDataWindowSplitterDistance"]));
            }
            set {
                this["MassModifyTableDataWindowSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TunerMinTableEquivalency {
            get {
                return ((int)(this["TunerMinTableEquivalency"]));
            }
            set {
                this["TunerMinTableEquivalency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TableEditorMinTableEquivalency {
            get {
                return ((int)(this["TableEditorMinTableEquivalency"]));
            }
            set {
                this["TableEditorMinTableEquivalency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int keyPressWait100ms {
            get {
                return ((int)(this["keyPressWait100ms"]));
            }
            set {
                this["keyPressWait100ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TableEditorMinOtherEquivalency {
            get {
                return ((int)(this["TableEditorMinOtherEquivalency"]));
            }
            set {
                this["TableEditorMinOtherEquivalency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MassCopyTableWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MassCopyTableWindowLocation"]));
            }
            set {
                this["MassCopyTableWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MassCopyTableWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MassCopyTableWindowState"]));
            }
            set {
                this["MassCopyTableWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MassCopyTableWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MassCopyTableWindowSize"]));
            }
            set {
                this["MassCopyTableWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MassCopyTableSplitHeight {
            get {
                return ((int)(this["MassCopyTableSplitHeight"]));
            }
            set {
                this["MassCopyTableSplitHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-new")]
        public string MassCopyTableFilenameExtra {
            get {
                return ((string)(this["MassCopyTableFilenameExtra"]));
            }
            set {
                this["MassCopyTableFilenameExtra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font TableExplorerFont {
            get {
                return ((global::System.Drawing.Font)(this["TableExplorerFont"]));
            }
            set {
                this["TableExplorerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int TableExplorerIconSize {
            get {
                return ((int)(this["TableExplorerIconSize"]));
            }
            set {
                this["TableExplorerIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TableExplorerWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TableExplorerWindowSize"]));
            }
            set {
                this["TableExplorerWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState TableExplorerWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["TableExplorerWindowState"]));
            }
            set {
                this["TableExplorerWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TableExplorerWindowPosition {
            get {
                return ((global::System.Drawing.Point)(this["TableExplorerWindowPosition"]));
            }
            set {
                this["TableExplorerWindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TableExplorerUseCategorySubfolder {
            get {
                return ((bool)(this["TableExplorerUseCategorySubfolder"]));
            }
            set {
                this["TableExplorerUseCategorySubfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TunerExplorerWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["TunerExplorerWindowLocation"]));
            }
            set {
                this["TunerExplorerWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState TunerExplorerWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["TunerExplorerWindowState"]));
            }
            set {
                this["TunerExplorerWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TunerExplorerWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["TunerExplorerWindowSize"]));
            }
            set {
                this["TunerExplorerWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TunerExplorerWindowSplitterDistance {
            get {
                return ((int)(this["TunerExplorerWindowSplitterDistance"]));
            }
            set {
                this["TunerExplorerWindowSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TunerExplorerWindowSplitter2Distance {
            get {
                return ((int)(this["TunerExplorerWindowSplitter2Distance"]));
            }
            set {
                this["TunerExplorerWindowSplitter2Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TunerTreeMode {
            get {
                return ((bool)(this["TunerTreeMode"]));
            }
            set {
                this["TunerTreeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TunerAutomulti1d {
            get {
                return ((bool)(this["TunerAutomulti1d"]));
            }
            set {
                this["TunerAutomulti1d"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TunerListModeTreeWidth {
            get {
                return ((int)(this["TunerListModeTreeWidth"]));
            }
            set {
                this["TunerListModeTreeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(". [ ]")]
        public string MulitableChars {
            get {
                return ((string)(this["MulitableChars"]));
            }
            set {
                this["MulitableChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableAutoFixChecksum {
            get {
                return ((bool)(this["DisableAutoFixChecksum"]));
            }
            set {
                this["DisableAutoFixChecksum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WorkingMode {
            get {
                return ((int)(this["WorkingMode"]));
            }
            set {
                this["WorkingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CvnPopupAccepted {
            get {
                return ((bool)(this["CvnPopupAccepted"]));
            }
            set {
                this["CvnPopupAccepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequireValidVerForStock {
            get {
                return ((bool)(this["RequireValidVerForStock"]));
            }
            set {
                this["RequireValidVerForStock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutomaticOpenImportedFile {
            get {
                return ((bool)(this["AutomaticOpenImportedFile"]));
            }
            set {
                this["AutomaticOpenImportedFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TunerShowUnitsUndefined {
            get {
                return ((bool)(this["TunerShowUnitsUndefined"]));
            }
            set {
                this["TunerShowUnitsUndefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TunerShowUnitsImperial {
            get {
                return ((bool)(this["TunerShowUnitsImperial"]));
            }
            set {
                this["TunerShowUnitsImperial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TunerShowUnitsMetric {
            get {
                return ((bool)(this["TunerShowUnitsMetric"]));
            }
            set {
                this["TunerShowUnitsMetric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SplashShowTime {
            get {
                return ((int)(this["SplashShowTime"]));
            }
            set {
                this["SplashShowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font PatcherLogFont {
            get {
                return ((global::System.Drawing.Font)(this["PatcherLogFont"]));
            }
            set {
                this["PatcherLogFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font DebugFont {
            get {
                return ((global::System.Drawing.Font)(this["DebugFont"]));
            }
            set {
                this["DebugFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool xdfImportUseTableName {
            get {
                return ((bool)(this["xdfImportUseTableName"]));
            }
            set {
                this["xdfImportUseTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCMHammer\\pcmhammer.exe")]
        public string FlashApp {
            get {
                return ((string)(this["FlashApp"]));
            }
            set {
                this["FlashApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--writecalibration $file")]
        public string FLashParams {
            get {
                return ((string)(this["FLashParams"]));
            }
            set {
                this["FLashParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoggerUseIntegrated {
            get {
                return ((bool)(this["LoggerUseIntegrated"]));
            }
            set {
                this["LoggerUseIntegrated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoggerExternalApp {
            get {
                return ((string)(this["LoggerExternalApp"]));
            }
            set {
                this["LoggerExternalApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoggerPort {
            get {
                return ((string)(this["LoggerPort"]));
            }
            set {
                this["LoggerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoggerLastProfile {
            get {
                return ((string)(this["LoggerLastProfile"]));
            }
            set {
                this["LoggerLastProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoggerLogFolder {
            get {
                return ((string)(this["LoggerLogFolder"]));
            }
            set {
                this["LoggerLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string LoggerLogSeparator {
            get {
                return ((string)(this["LoggerLogSeparator"]));
            }
            set {
                this["LoggerLogSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string J2534Device {
            get {
                return ((string)(this["J2534Device"]));
            }
            set {
                this["J2534Device"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoggerPassive {
            get {
                return ((bool)(this["LoggerPassive"]));
            }
            set {
                this["LoggerPassive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoggerUseJ2534 {
            get {
                return ((bool)(this["LoggerUseJ2534"]));
            }
            set {
                this["LoggerUseJ2534"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoggerSerialDeviceType {
            get {
                return ((string)(this["LoggerSerialDeviceType"]));
            }
            set {
                this["LoggerSerialDeviceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SendOnce")]
        public string LoggerResponseMode {
            get {
                return ((string)(this["LoggerResponseMode"]));
            }
            set {
                this["LoggerResponseMode"] = value;
            }
        }
    }
}
