using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace UniversalPatcher
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("SW-CNT", Namespace = "", IsNullable = false)]
    public partial class SWCNT
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ABLAEUFE", typeof(SWCNTABLAEUFE), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DATEN", typeof(SWCNTDATEN), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("IDENT", typeof(SWCNTIDENT), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("INFO", typeof(SWCNTINFO), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFE
    {

        private SWCNTABLAEUFEABLAUF[] aBLAUFField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ABLAUF", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTABLAEUFEABLAUF[] ABLAUF
        {
            get
            {
                return this.aBLAUFField;
            }
            set
            {
                this.aBLAUFField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFEABLAUF
    {

        private string aBLAUFNAMEField;

        private SWCNTABLAEUFEABLAUFKWP2000[] kWP2000Field;

        private SWCNTABLAEUFEABLAUFDATENVERWEISEDATENVERWEIS[] dATENVERWEISEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ABLAUF-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ABLAUFNAME
        {
            get
            {
                return this.aBLAUFNAMEField;
            }
            set
            {
                this.aBLAUFNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTABLAEUFEABLAUFKWP2000[] KWP2000
        {
            get
            {
                return this.kWP2000Field;
            }
            set
            {
                this.kWP2000Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("DATEN-VERWEISE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DATEN-VERWEIS", typeof(SWCNTABLAEUFEABLAUFDATENVERWEISEDATENVERWEIS), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTABLAEUFEABLAUFDATENVERWEISEDATENVERWEIS[] DATENVERWEISE
        {
            get
            {
                return this.dATENVERWEISEField;
            }
            set
            {
                this.dATENVERWEISEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFEABLAUFKWP2000
    {

        private string kWP2000TGTField;

        private string kWP2000SA2Field;

        private SWCNTABLAEUFEABLAUFKWP2000BAUDRATEN2000BAUDRATE2000[] bAUDRATEN2000Field;

        private SWCNTABLAEUFEABLAUFKWP2000KWP2000REI[] kWP2000REIField;

        private SWCNTABLAEUFEABLAUFKWP2000KWP2000ACP[] kWP2000ACPField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-TGT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000TGT
        {
            get
            {
                return this.kWP2000TGTField;
            }
            set
            {
                this.kWP2000TGTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-SA2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000SA2
        {
            get
            {
                return this.kWP2000SA2Field;
            }
            set
            {
                this.kWP2000SA2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("BAUDRATEN-2000", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BAUDRATE-2000", typeof(SWCNTABLAEUFEABLAUFKWP2000BAUDRATEN2000BAUDRATE2000), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SWCNTABLAEUFEABLAUFKWP2000BAUDRATEN2000BAUDRATE2000[] BAUDRATEN2000
        {
            get
            {
                return this.bAUDRATEN2000Field;
            }
            set
            {
                this.bAUDRATEN2000Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-REI", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTABLAEUFEABLAUFKWP2000KWP2000REI[] KWP2000REI
        {
            get
            {
                return this.kWP2000REIField;
            }
            set
            {
                this.kWP2000REIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-ACP", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTABLAEUFEABLAUFKWP2000KWP2000ACP[] KWP2000ACP
        {
            get
            {
                return this.kWP2000ACPField;
            }
            set
            {
                this.kWP2000ACPField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFEABLAUFKWP2000BAUDRATEN2000BAUDRATE2000
    {

        private string bAUDRATETESTERField;

        private string bAUDRATESGField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BAUDRATE-TESTER", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BAUDRATETESTER
        {
            get
            {
                return this.bAUDRATETESTERField;
            }
            set
            {
                this.bAUDRATETESTERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BAUDRATE-SG", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BAUDRATESG
        {
            get
            {
                return this.bAUDRATESGField;
            }
            set
            {
                this.bAUDRATESGField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFEABLAUFKWP2000KWP2000REI
    {

        private string kWP2000PSTATBIT0Field;

        private string kWP2000PSTATBIT1Field;

        private string kWP2000PSTATBIT2Field;

        private string kWP2000PSTATBIT3Field;

        private string kWP2000PSTATBIT4Field;

        private string kWP2000PSTATBIT5Field;

        private string kWP2000PSTATBIT6Field;

        private string kWP2000PSTATBIT7Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT0", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT0
        {
            get
            {
                return this.kWP2000PSTATBIT0Field;
            }
            set
            {
                this.kWP2000PSTATBIT0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT1
        {
            get
            {
                return this.kWP2000PSTATBIT1Field;
            }
            set
            {
                this.kWP2000PSTATBIT1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT2
        {
            get
            {
                return this.kWP2000PSTATBIT2Field;
            }
            set
            {
                this.kWP2000PSTATBIT2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT3", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT3
        {
            get
            {
                return this.kWP2000PSTATBIT3Field;
            }
            set
            {
                this.kWP2000PSTATBIT3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT4", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT4
        {
            get
            {
                return this.kWP2000PSTATBIT4Field;
            }
            set
            {
                this.kWP2000PSTATBIT4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT5", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT5
        {
            get
            {
                return this.kWP2000PSTATBIT5Field;
            }
            set
            {
                this.kWP2000PSTATBIT5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT6
        {
            get
            {
                return this.kWP2000PSTATBIT6Field;
            }
            set
            {
                this.kWP2000PSTATBIT6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-PSTAT-BIT7", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000PSTATBIT7
        {
            get
            {
                return this.kWP2000PSTATBIT7Field;
            }
            set
            {
                this.kWP2000PSTATBIT7Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFEABLAUFKWP2000KWP2000ACP
    {

        private string kWP2000P2MINField;

        private string kWP2000P2MAXField;

        private string kWP2000P3MINField;

        private string kWP2000P3MAXField;

        private string kWP2000P4MINField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-P2MIN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000P2MIN
        {
            get
            {
                return this.kWP2000P2MINField;
            }
            set
            {
                this.kWP2000P2MINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-P2MAX", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000P2MAX
        {
            get
            {
                return this.kWP2000P2MAXField;
            }
            set
            {
                this.kWP2000P2MAXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-P3MIN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000P3MIN
        {
            get
            {
                return this.kWP2000P3MINField;
            }
            set
            {
                this.kWP2000P3MINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-P3MAX", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000P3MAX
        {
            get
            {
                return this.kWP2000P3MAXField;
            }
            set
            {
                this.kWP2000P3MAXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KWP-2000-P4MIN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KWP2000P4MIN
        {
            get
            {
                return this.kWP2000P4MINField;
            }
            set
            {
                this.kWP2000P4MINField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTABLAEUFEABLAUFDATENVERWEISEDATENVERWEIS
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTDATEN
    {

        private SWCNTDATENDATENBLOECKEDATENBLOCK[] dATENBLOECKEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DATENBLOCK", typeof(SWCNTDATENDATENBLOECKEDATENBLOCK), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SWCNTDATENDATENBLOECKEDATENBLOCK[] DATENBLOECKE
        {
            get
            {
                return this.dATENBLOECKEField;
            }
            set
            {
                this.dATENBLOECKEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTDATENDATENBLOECKEDATENBLOCK
    {

        private string dATENBLOCKNAMEField;

        private string dATENBLOCKFORMATNAMEField;

        private string sTARTADRField;

        private string eNDADRField;

        private string dATENBLOCKFORMATField;

        private string gROESSEDEKOMPRIMIERTField;

        private string dATENBLOCKDATENField;

        private SWCNTDATENDATENBLOECKEDATENBLOCKLOESCHBEREICH[] lOESCHBEREICHField;

        private SWCNTDATENDATENBLOECKEDATENBLOCKDATENBLOCKCHECK[] dATENBLOCKCHECKField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATENBLOCK-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATENBLOCKNAME
        {
            get
            {
                return this.dATENBLOCKNAMEField;
            }
            set
            {
                this.dATENBLOCKNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATENBLOCK-FORMAT-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATENBLOCKFORMATNAME
        {
            get
            {
                return this.dATENBLOCKFORMATNAMEField;
            }
            set
            {
                this.dATENBLOCKFORMATNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-ADR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTADR
        {
            get
            {
                return this.sTARTADRField;
            }
            set
            {
                this.sTARTADRField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("END-ADR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDADR
        {
            get
            {
                return this.eNDADRField;
            }
            set
            {
                this.eNDADRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATENBLOCK-FORMAT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATENBLOCKFORMAT
        {
            get
            {
                return this.dATENBLOCKFORMATField;
            }
            set
            {
                this.dATENBLOCKFORMATField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GROESSE-DEKOMPRIMIERT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROESSEDEKOMPRIMIERT
        {
            get
            {
                return this.gROESSEDEKOMPRIMIERTField;
            }
            set
            {
                this.gROESSEDEKOMPRIMIERTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATENBLOCK-DATEN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATENBLOCKDATEN
        {
            get
            {
                return this.dATENBLOCKDATENField;
            }
            set
            {
                this.dATENBLOCKDATENField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LOESCH-BEREICH", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTDATENDATENBLOECKEDATENBLOCKLOESCHBEREICH[] LOESCHBEREICH
        {
            get
            {
                return this.lOESCHBEREICHField;
            }
            set
            {
                this.lOESCHBEREICHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATENBLOCK-CHECK", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SWCNTDATENDATENBLOECKEDATENBLOCKDATENBLOCKCHECK[] DATENBLOCKCHECK
        {
            get
            {
                return this.dATENBLOCKCHECKField;
            }
            set
            {
                this.dATENBLOCKCHECKField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTDATENDATENBLOECKEDATENBLOCKLOESCHBEREICH
    {

        private string sTARTADRField;

        private string eNDADRField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-ADR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTADR
        {
            get
            {
                return this.sTARTADRField;
            }
            set
            {
                this.sTARTADRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-ADR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDADR
        {
            get
            {
                return this.eNDADRField;
            }
            set
            {
                this.eNDADRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTDATENDATENBLOECKEDATENBLOCKDATENBLOCKCHECK
    {

        private string sTARTADRField;

        private string eNDADRField;

        private string cHECKSUMMEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-ADR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTADR
        {
            get
            {
                return this.sTARTADRField;
            }
            set
            {
                this.sTARTADRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-ADR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDADR
        {
            get
            {
                return this.eNDADRField;
            }
            set
            {
                this.eNDADRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHECKSUMME
        {
            get
            {
                return this.cHECKSUMMEField;
            }
            set
            {
                this.cHECKSUMMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTIDENT
    {

        private string cNTDATEIField;

        private string cNTVERSIONTYPField;

        private string cNTVERSIONINHALTField;

        private string cNTIDENTTEXTField;

        private string sWVERSIONKURZField;

        private string sWVERSIONLANGField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNT-DATEI", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNTDATEI
        {
            get
            {
                return this.cNTDATEIField;
            }
            set
            {
                this.cNTDATEIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNT-VERSION-TYP", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNTVERSIONTYP
        {
            get
            {
                return this.cNTVERSIONTYPField;
            }
            set
            {
                this.cNTVERSIONTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNT-VERSION-INHALT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNTVERSIONINHALT
        {
            get
            {
                return this.cNTVERSIONINHALTField;
            }
            set
            {
                this.cNTVERSIONINHALTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNT-IDENT-TEXT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNTIDENTTEXT
        {
            get
            {
                return this.cNTIDENTTEXTField;
            }
            set
            {
                this.cNTIDENTTEXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SW-VERSION-KURZ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SWVERSIONKURZ
        {
            get
            {
                return this.sWVERSIONKURZField;
            }
            set
            {
                this.sWVERSIONKURZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SW-VERSION-LANG", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SWVERSIONLANG
        {
            get
            {
                return this.sWVERSIONLANGField;
            }
            set
            {
                this.sWVERSIONLANGField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTINFO
    {

        private SWCNTINFOADRESSENADRESSE[] aDRESSENField;

        private SWCNTINFOREVISIONENREVISION[] rEVISIONENField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ADRESSE", typeof(SWCNTINFOADRESSENADRESSE), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SWCNTINFOADRESSENADRESSE[] ADRESSEN
        {
            get
            {
                return this.aDRESSENField;
            }
            set
            {
                this.aDRESSENField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("REVISION", typeof(SWCNTINFOREVISIONENREVISION), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SWCNTINFOREVISIONENREVISION[] REVISIONEN
        {
            get
            {
                return this.rEVISIONENField;
            }
            set
            {
                this.rEVISIONENField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTINFOADRESSENADRESSE
    {

        private string fIRMENNAMEField;

        private string rOLLEField;

        private string aBTEILUNGField;

        private string pERSONField;

        private string aNSCHRIFTField;

        private string tELEFONField;

        private string fAXField;

        private string eMAILField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIRMENNAME
        {
            get
            {
                return this.fIRMENNAMEField;
            }
            set
            {
                this.fIRMENNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ROLLE
        {
            get
            {
                return this.rOLLEField;
            }
            set
            {
                this.rOLLEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ABTEILUNG
        {
            get
            {
                return this.aBTEILUNGField;
            }
            set
            {
                this.aBTEILUNGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERSON
        {
            get
            {
                return this.pERSONField;
            }
            set
            {
                this.pERSONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANSCHRIFT
        {
            get
            {
                return this.aNSCHRIFTField;
            }
            set
            {
                this.aNSCHRIFTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFON
        {
            get
            {
                return this.tELEFONField;
            }
            set
            {
                this.tELEFONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FAX
        {
            get
            {
                return this.fAXField;
            }
            set
            {
                this.fAXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SWCNTINFOREVISIONENREVISION
    {

        private string wANNField;

        private string wERField;

        private string wASField;

        private string wARUMField;

        private string vERSIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WANN
        {
            get
            {
                return this.wANNField;
            }
            set
            {
                this.wANNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WER
        {
            get
            {
                return this.wERField;
            }
            set
            {
                this.wERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAS
        {
            get
            {
                return this.wASField;
            }
            set
            {
                this.wASField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WARUM
        {
            get
            {
                return this.wARUMField;
            }
            set
            {
                this.wARUMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSION
        {
            get
            {
                return this.vERSIONField;
            }
            set
            {
                this.vERSIONField = value;
            }
        }
    }
}
